import type { DashboardAction, DashboardRealtimeMessage } from '@/shared/types/realtime'

export type RealtimeHandler = (message: DashboardRealtimeMessage) => void

export type DashboardRealtimeClient = {
  connect: () => void
  disconnect: () => void
  sendAction: (action: DashboardAction) => void
  subscribe: (handler: RealtimeHandler) => () => void
}

const DEFAULT_AGENT = { id: 'analysis', name: 'Analysis', status: 'running' as const }

function buildMockSnapshot(message: string): DashboardRealtimeMessage {
  const now = new Date().toISOString()
  return {
    type: 'snapshot',
    payload: {
      activeAgent: DEFAULT_AGENT,
      reasoning: `Mock reasoning for: ${message}`,
      conclusion: 'Mock conclusion generated by the local stream.',
      finalResponse: `Mock response: ${message}`,
      events: [
        {
          id: crypto.randomUUID(),
          kind: 'action',
          title: 'Action queued',
          detail: message,
          at: now,
          agentId: DEFAULT_AGENT.id,
        },
        {
          id: crypto.randomUUID(),
          kind: 'success',
          title: 'Action processed',
          detail: 'Dashboard mock event stream',
          at: now,
          agentId: DEFAULT_AGENT.id,
        },
      ],
      logs: [
        { id: crypto.randomUUID(), level: 'info', message: `Sent action: ${message}`, at: now },
        { id: crypto.randomUUID(), level: 'info', message: 'Mock websocket accepted action', at: now },
      ],
      tokens: { prompt: 12, completion: 18, total: 30 },
    },
  }
}

export function createDashboardRealtimeClient(_url?: string): DashboardRealtimeClient {
  const listeners = new Set<RealtimeHandler>()
  let intervalId: number | undefined
  let socket: WebSocket | null = null
  let fallbackTimer: number | undefined
  let receivedRemoteMessage = false
  let manualDisconnect = false
  let mode: 'mock' | 'websocket' = 'mock'

  const emit = (message: DashboardRealtimeMessage) => {
    listeners.forEach((handler) => handler(message))
  }

  const connect = () => {
    if (_url && typeof window !== 'undefined' && 'WebSocket' in window) {
      mode = 'websocket'
      socket = new WebSocket(_url)
      receivedRemoteMessage = false
      manualDisconnect = false
      fallbackTimer = window.setTimeout(() => {
        if (!receivedRemoteMessage && socket?.readyState !== WebSocket.OPEN) {
          socket = null
          mode = 'mock'
          emit({ type: 'status', payload: { connected: true, mode } })
          emit(buildMockSnapshot('frontend dashboard boot'))
        }
      }, 1200)
      socket.onopen = () => emit({ type: 'status', payload: { connected: true, mode } })
      socket.onclose = () => {
        if (manualDisconnect) {
          emit({ type: 'status', payload: { connected: false, mode } })
          return
        }
        if (fallbackTimer) window.clearTimeout(fallbackTimer)
        if (!receivedRemoteMessage) {
          socket = null
          mode = 'mock'
          emit({ type: 'status', payload: { connected: true, mode } })
          emit(buildMockSnapshot('frontend dashboard boot'))
          return
        }
        emit({ type: 'status', payload: { connected: false, mode } })
      }
      socket.onerror = () => {
        if (fallbackTimer) window.clearTimeout(fallbackTimer)
        if (!receivedRemoteMessage) {
          socket = null
          mode = 'mock'
          emit({ type: 'status', payload: { connected: true, mode } })
          emit(buildMockSnapshot('frontend dashboard boot'))
          return
        }
        emit({ type: 'status', payload: { connected: false, mode } })
      }
      socket.onmessage = (event) => {
        receivedRemoteMessage = true
        if (fallbackTimer) {
          window.clearTimeout(fallbackTimer)
          fallbackTimer = undefined
        }
        try {
          const parsed = JSON.parse(String(event.data)) as DashboardRealtimeMessage
          emit(parsed)
        } catch {
          emit({
            type: 'log',
            payload: {
              id: crypto.randomUUID(),
              level: 'warn',
              message: 'Received non-JSON websocket payload',
              at: new Date().toISOString(),
            },
          })
        }
      }
      return
    }

    emit({ type: 'status', payload: { connected: true, mode } })
    if (intervalId) return
    intervalId = window.setInterval(() => {
      emit({
        type: 'log',
        payload: {
          id: crypto.randomUUID(),
          level: 'debug',
          message: 'Mock heartbeat from realtime layer',
          at: new Date().toISOString(),
        },
      })
    }, 8000)
  }

  const disconnect = () => {
    manualDisconnect = true
    socket?.close()
    socket = null
    if (fallbackTimer) {
      window.clearTimeout(fallbackTimer)
      fallbackTimer = undefined
    }
    if (intervalId) {
      window.clearInterval(intervalId)
      intervalId = undefined
    }
    emit({ type: 'status', payload: { connected: false, mode } })
  }

  const sendAction = (action: DashboardAction) => {
    if (socket?.readyState === WebSocket.OPEN) {
      socket.send(JSON.stringify({ type: 'action', payload: action }))
      return
    }
    emit(buildMockSnapshot(action.message))
  }

  const subscribe = (handler: RealtimeHandler) => {
    listeners.add(handler)
    return () => listeners.delete(handler)
  }

  return { connect, disconnect, sendAction, subscribe }
}
